// Auto-generated by scripts/fetch-svgl.mjs — do not edit manually.
// Run: node scripts/fetch-svgl.mjs

const RAW: Array<[string, string, string]> = [];

const assetBase = process.env.NODE_ENV === "production" ? "/sublist-web" : "";

export const SVGL_MAP: Record<string, string> = Object.fromEntries(
  RAW.flatMap(([fileKey, titleSlug]) => {
    const path = `${assetBase}/assets/svgl/${fileKey}.svg`;
    const keys = new Set([fileKey, titleSlug, fileKey.replace(/-/g, "")]);
    return [...keys].map((k) => [k, path]);
  })
);

export function searchSvglLocal(
  query: string
): Array<{ slug: string; title: string; path: string }> {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();
  const qSlug = q.replace(/[^a-z0-9]/g, "");
  const seen = new Set<string>();
  return RAW.filter(([fileKey, titleSlug, title]) => {
    if (seen.has(fileKey)) return false;
    seen.add(fileKey);
    return title.toLowerCase().includes(q) || titleSlug.includes(qSlug);
  })
    .slice(0, 24)
    .map(([fileKey, titleSlug, title]) => ({
      slug: titleSlug,
      title,
      path: `${assetBase}/assets/svgl/${fileKey}.svg`,
    }));
}
