// Downloads all SVG icons from svgl.app and generates src/lib/svgl-local.ts
// Usage: node scripts/fetch-svgl.mjs

import { writeFileSync, mkdirSync, existsSync } from "node:fs";

const API_URL  = "https://svgl.app/api/svgs";
const OUT_DIR  = "public/assets/svgl";
const MAP_FILE = "src/lib/svgl-local.ts";

function toSlug(str) {
  return str.toLowerCase().replace(/[^a-z0-9]/g, "");
}

async function main() {
  console.log("Fetching svgl icon list…");
  const res = await fetch(API_URL);
  const icons = await res.json();
  console.log(`Found ${icons.length} icons`);

  mkdirSync(OUT_DIR, { recursive: true });

  // Build entry list
  const entries = [];
  for (const icon of icons) {
    const route = typeof icon.route === "string" ? icon.route : icon.route?.light;
    if (!route) continue;
    const filename = route.split("/").pop();
    if (!filename?.endsWith(".svg")) continue;
    entries.push({
      fileKey:   filename.replace(".svg", ""),   // e.g. "prime-video", "disneyplus"
      titleSlug: toSlug(icon.title),              // e.g. "primevideo", "disney"
      title:     icon.title,
      filename,
      route,
    });
  }

  // Download in batches of 10
  let done = 0, failed = 0;
  for (let i = 0; i < entries.length; i += 10) {
    const batch = entries.slice(i, i + 10);
    await Promise.all(batch.map(async (e) => {
      const outPath = `${OUT_DIR}/${e.filename}`;
      if (existsSync(outPath)) { done++; return; }
      try {
        const r = await fetch(e.route);
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        writeFileSync(outPath, await r.text());
        done++;
      } catch (err) {
        console.warn(`  FAIL ${e.title}: ${err.message}`);
        failed++;
      }
    }));
    if (i % 100 === 0 && i > 0) console.log(`  ${done}/${entries.length}…`);
  }
  console.log(`Downloaded: ${done}  Failed: ${failed}`);

  // Generate TypeScript map file
  const rows = entries
    .map((e) => `  ${JSON.stringify([e.fileKey, e.titleSlug, e.title])}`)
    .join(",\n");

  const ts = `// Auto-generated by scripts/fetch-svgl.mjs — do not edit manually.
// Re-run: node scripts/fetch-svgl.mjs

const RAW: Array<[string, string, string]> = [
${rows},
];

const assetBase = process.env.NODE_ENV === "production" ? "/sublist-web" : "";

// Maps every known key variant → local SVG path
export const SVGL_MAP: Record<string, string> = Object.fromEntries(
  RAW.flatMap(([fileKey, titleSlug]) => {
    const path = \`\${assetBase}/assets/svgl/\${fileKey}.svg\`;
    const keys = new Set([fileKey, titleSlug, fileKey.replace(/-/g, "")]);
    return [...keys].map((k) => [k, path]);
  })
);

export function searchSvglLocal(
  query: string
): Array<{ slug: string; title: string; path: string }> {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();
  const qSlug = q.replace(/[^a-z0-9]/g, "");
  const seen = new Set<string>();
  return RAW.filter(([fileKey, titleSlug, title]) => {
    if (seen.has(fileKey)) return false;
    seen.add(fileKey);
    return title.toLowerCase().includes(q) || titleSlug.includes(qSlug);
  })
    .slice(0, 24)
    .map(([fileKey, titleSlug, title]) => ({
      slug: titleSlug,
      title,
      path: \`\${assetBase}/assets/svgl/\${fileKey}.svg\`,
    }));
}
`;

  writeFileSync(MAP_FILE, ts);
  console.log(`Map written to ${MAP_FILE}`);
}

main().catch(console.error);
