// Downloads all SVG icons from svgl and generates src/lib/svgl-local.ts
// Usage: node scripts/fetch-svgl.mjs
//
// Sources tried in order:
//   1. https://api.svgl.app  (official REST API)
//   2. GitHub raw TS data file + raw SVG files (reliable fallback)

import { writeFileSync, mkdirSync, existsSync } from "node:fs";

const API_URL       = "https://api.svgl.app";
const GH_DATA_URL   = "https://raw.githubusercontent.com/pheralb/svgl/main/src/data/svgs.ts";
const GH_SVG_BASE   = "https://raw.githubusercontent.com/pheralb/svgl/main/static";
const SVGL_BASE     = "https://svgl.app";
const OUT_DIR       = "public/assets/svgl";
const MAP_FILE      = "src/lib/svgl-local.ts";

function toSlug(str) {
  return str.toLowerCase().replace(/[^a-z0-9]/g, "");
}

async function fetchIconList() {
  // Try official API first
  try {
    const res = await fetch(API_URL, {
      headers: { Accept: "application/json", "User-Agent": "sublist-web/1.0" },
    });
    if (res.ok) {
      const data = await res.json();
      if (Array.isArray(data) && data.length > 0) {
        console.log(`[API] ${data.length} icons`);
        return { icons: data, svgBase: SVGL_BASE };
      }
    }
    console.warn(`[API] status ${res.status} — falling back to GitHub raw`);
  } catch (err) {
    console.warn(`[API] ${err.message} — falling back to GitHub raw`);
  }

  // Fallback: parse the TypeScript data file from GitHub
  console.log("Fetching icon list from GitHub raw…");
  const tsRes = await fetch(GH_DATA_URL);
  if (!tsRes.ok) throw new Error(`GitHub data fetch failed: ${tsRes.status}`);
  const ts = await tsRes.text();

  const js = ts
    .split("\n")
    .filter((l) => !l.startsWith("import "))
    .map((l) => l.replace(/^export const svgs: iSVG\[\] = \[/, "return ["))
    .join("\n");

  const icons = new Function(js)();
  if (!Array.isArray(icons) || icons.length === 0) throw new Error("Failed to parse TypeScript data");
  console.log(`[GitHub] ${icons.length} icons`);
  return { icons, svgBase: GH_SVG_BASE };
}

async function main() {
  console.log("Fetching svgl icon list…");
  const { icons, svgBase } = await fetchIconList();

  mkdirSync(OUT_DIR, { recursive: true });

  // Build entry list
  const entries = [];
  for (const icon of icons) {
    const route = typeof icon.route === "string" ? icon.route : icon.route?.light;
    if (!route) continue;
    const filename = route.split("/").pop();
    if (!filename?.endsWith(".svg")) continue;

    // Build absolute download URL
    const downloadUrl = route.startsWith("http") ? route : `${svgBase}${route}`;

    entries.push({
      fileKey:     filename.replace(".svg", ""),
      titleSlug:   toSlug(icon.title),
      title:       icon.title,
      filename,
      downloadUrl,
    });
  }

  // Download in batches of 10
  let done = 0, failed = 0;
  for (let i = 0; i < entries.length; i += 10) {
    const batch = entries.slice(i, i + 10);
    await Promise.all(batch.map(async (e) => {
      const outPath = `${OUT_DIR}/${e.filename}`;
      if (existsSync(outPath)) { done++; return; }
      try {
        const r = await fetch(e.downloadUrl);
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        writeFileSync(outPath, await r.text());
        done++;
      } catch (err) {
        console.warn(`  FAIL ${e.title}: ${err.message}`);
        failed++;
      }
    }));
    if (i % 100 === 0 && i > 0) console.log(`  ${done}/${entries.length}…`);
  }
  console.log(`Downloaded: ${done}  Failed: ${failed}`);

  // Generate TypeScript map file
  const rows = entries
    .map((e) => `  ${JSON.stringify([e.fileKey, e.titleSlug, e.title])}`)
    .join(",\n");

  const ts = `// Auto-generated by scripts/fetch-svgl.mjs — do not edit manually.
// Re-run: node scripts/fetch-svgl.mjs

const RAW: Array<[string, string, string]> = [
${rows},
];

const assetBase = process.env.NODE_ENV === "production" ? "/sublist-web" : "";

// Maps every known key variant → local SVG path
export const SVGL_MAP: Record<string, string> = Object.fromEntries(
  RAW.flatMap(([fileKey, titleSlug]) => {
    const path = \`\${assetBase}/assets/svgl/\${fileKey}.svg\`;
    const keys = new Set([fileKey, titleSlug, fileKey.replace(/-/g, "")]);
    return [...keys].map((k) => [k, path]);
  })
);

export function searchSvglLocal(
  query: string
): Array<{ slug: string; title: string; path: string }> {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();
  const qSlug = q.replace(/[^a-z0-9]/g, "");
  const seen = new Set<string>();
  return RAW.filter(([fileKey, titleSlug, title]) => {
    if (seen.has(fileKey)) return false;
    seen.add(fileKey);
    return title.toLowerCase().includes(q) || titleSlug.includes(qSlug);
  })
    .slice(0, 24)
    .map(([fileKey, titleSlug, title]) => ({
      slug: titleSlug,
      title,
      path: \`\${assetBase}/assets/svgl/\${fileKey}.svg\`,
    }));
}
`;

  writeFileSync(MAP_FILE, ts);
  console.log(`Map written to ${MAP_FILE}`);
}

main().catch(console.error);
